[pre-commit]
parallel = true

[[pre-commit.jobs]]
run = "mise format"
stage_fixed = true
glob = "*.go"

[[pre-commit.jobs]]
run = "mise deps"
glob = ["*.go", "go.mod", "go.sum"]

[[pre-commit.jobs]]
run = "mise lint"
glob = "*.go"

[[pre-commit.jobs]]
run = "mise test"
glob = "*.go"

[[pre-commit.jobs]]
run = "mise docs-sync"
stage_fixed = true
glob = "*.go"
